spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none # use liquibase for migrations instead of auto-creating schema
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
